# GWEI CONTROL
MAX_GAS = 40

# GAS CONTROL
GAS_MULTIPLAYER = 0.8

# TAKE THE WALLETS IN RANDOM ORDER
RANDOM_WALLETS = True

# REMOVE WALLET FROM FILES AFTER WORK
REMOVE_WALLET = True

# PROXY MODE
USE_PROXY = True

# THREADS CONTROLS
MAX_WORKERS = 4
WORKER_SLEEP_FROM = 40 # Seconds
WORKER_SLEEP_TO = 80 # Seconds

# SLEEPS AFTER WORK
SLEEP_AFTER_WORK_FROM = 60 # Seconds
SLEEP_AFTER_WORK_TO = 120 # Seconds

# RPC
ZKSYNC_RPC = 'https://mainnet.era.zksync.io'

# SLIPPAGE FOR SWAPS
SLIPPAGE = 5